### PR TITLE
Final version of the VPP is available.

### PR DESCRIPTION
**Pull request by theangelogarci**
Final version of the visual paradigm project is done, check it out.

### CODE REVIEW

**Comment by luissanty2** [comment]
We rock 😎

**Comment by Carlos-Bernalte** [comment]
Nice! Great job guys!

**Review by Sergio-Silvestre — APPROVED** [review]
It seems to be ok for me. Nice job!

**Comment by Josue-Zenteno** [comment]
Huge amounts of professional work

**Review by Josue-Zenteno — COMMENTED** [review]
:+1:

**Review by Josue-Zenteno — APPROVED** [review]

**Pull request merged**
